### ISSUE TITLE
Unable to create a character or login with an account that has a character already created.

### ISSUE THREAD

**Issue by q98** [suriyun-mmorpg/UnityMultiplayerARPG_MMO.NET#1]
Attached is the error I receive after logging in and either creating a character or, logging in then arriving at the character selection screen.

Note:this is a fresh build after pulling from here, and freshly importing the project from the asset store - the asset store server works as intended but this server nets me this error.

ArgumentException: Argument_InvalidOffLen
System.ArraySegment`1[T]..ctor (System.Byte[] array, System.Int32 offset, System.Int32 count) (at <27124aa0e30a41659b903b822b959bc7>:0)
LiteNetLib.Utils.NetDataReader.GetBytesSegment (System.Int32 count) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/LiteNetLib/Utils/NetDataReader.cs:323)
LiteNetLib.Utils.NetDataReader.GetString () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/LiteNetLib/Utils/NetDataReader.cs:316)
MultiplayerARPG.CharacterItem.Deserialize (LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/SharedData/Scripts/CharacterData/RelatesData/CharacterItem.cs:191)
LiteNetLib.Utils.NetDataReader.Get[T] (System.Func`1[TResult] constructor) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/LiteNetLib/Utils/NetDataReader.cs:345)
MultiplayerARPG.PlayerCharacterDataExtensions.DeserializeCharacterData[T] (T characterData, LiteNetLib.Utils.NetDataReader reader, System.Boolean withTransforms, System.Boolean withEquipWeapons, System.Boolean withAttributes, System.Boolean withSkills, System.Boolean withSkillUsages, System.Boolean withBuffs, System.Boolean withEquipItems, System.Boolean withNonEquipItems, System.Boolean withSummons, System.Boolean withHotkeys, System.Boolean withQuests, System.Boolean withCurrencies, System.Boolean withServerCustomData, System.Boolean withPrivateCustomData, System.Boolean withPublicCustomData) (at Assets/UnityMultiplayerARPG/Core/SharedData/Scripts/CharacterData/PlayerCharacterDataExtensions.cs:471)
MultiplayerARPG.MMO.ResponseCharactersMessage.Deserialize (LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Src/Central/Messages/Character/ResponseCharactersMessage.cs:20)
LiteNetLibManager.LiteNetLibResponseHandler`2[TRequest,TResponse].InvokeResponse (LiteNetLibManager.ResponseHandlerData responseHandlerData, LiteNetLibManager.AckResponseCode responseCode, LiteNetLibManager.ResponseDelegate`1[TResponse] anotherResponseHandler) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/RequestResponse/LiteNetLibResponseHandler.cs:30)
LiteNetLibManager.LiteNetLibRequestCallback.Response (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader, LiteNetLibManager.AckResponseCode responseCode) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/RequestResponse/LiteNetLibRequestCallback.cs:31)
LiteNetLibManager.TransportHandler.ProceedResponse (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:235)
LiteNetLibManager.TransportHandler.ReadPacket (System.Int64 connectionId, LiteNetLib.Utils.NetDataReader reader) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/TransportHandler.cs:73)
LiteNetLibManager.LiteNetLibClient.OnClientReceive (LiteNetLibManager.TransportEventData eventData) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:77)
LiteNetLibManager.LiteNetLibClient.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibClient.cs:36)
LiteNetLibManager.LiteNetLibManager.Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Scripts/LiteNetLibManager.cs:150)
MultiplayerARPG.MMO.CentralNetworkManager.Update () (at Assets/UnityMultiplayerARPG/MMO/Scripts/MMOGame/Src/Central/CentralNetworkManager.cs:137)

I've gone through a few times trying to figure it out but ultimately I fail 🤣 any help would be appreciated

**Comment by insthync** [comment]
Hello, try to export data button from game instance component

![Screenshot_37](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO.NET/assets/2697550/e7d523f2-a31c-49bd-a36f-5e68e699e47b)

To export it to this project -> Configs folder

**Comment by insthync** [comment]
Yes, it can be related

**Comment by q98** [comment]
@insthync any ideas on a fix?

**Comment by insthync** [comment]
May check out on the version which match to your game or just download and use latest version which was uploaded yesterday.
